config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :articles

  resources :categories, except: [:destroy]

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base

  # Relationship
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  # Validation
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # Before Show, edit, update, destroy actions, set_article private method is called
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      # Successfully saved the article, redirect to show method
      flash[:success] = 'Article was successfully created!'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated!'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted!'
    redirect_to articles_path
  end

  private
  def article_params
    # Whitelist some article fields
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own articles.'
      redirect_to articles_path
    end
  end

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
              <small>Created by <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated <%= time_ago_in_words(article.updated_at) %></small>
            </div>
          </div>
          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>
          <%= link_to '', article_url(article) + '#disqus_thread' %>
          <div class="article-actions">
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <%=  link_to 'Edit', edit_article_path(article), class: 'btn btn-xs btn-primary' %>
              <%= link_to 'Delete this article',
                          article_path(article),
                          method: :delete,
                          class: 'btn btn-xs btn-danger',
                          data: { confirm: 'Are you sure you want to delete this article?'} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script id="dsq-count-scr" src="//kersuzanalphablog.disqus.com/count.js" async></script>

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
  /**
   * RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   * LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
   */

   var disqus_config = function () {
    this.page.url = '<%= url_for([@article, { only_path: false }]) %>'; // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @article.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    this.page.title = '<%= @article.title %>';
    this.page.shortname = 'kersuzanalphablog';
   };

  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = '//kersuzanalphablog.disqus.com/embed.js';

    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: 'form-horizontal', role: 'form' }) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true  %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: 'form-control', placeholder: 'Body of article', rows: 10 %>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <%= cb.label(class: 'checkbox-inline input-checkbox') {cb.check_box(class: 'checkbox') + cb.text } %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <%= f.submit(@article.new_record? ? 'Create article' : 'Update article', class: 'btn btn-primary btn-large') %>
          </div>
        </div>
    <% end %>
    <div align="center">
      [<%= link_to 'Cancel and back to articles listing', articles_path %>]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 align="center">Edit existing article</h1>

  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1 align="center">Listing all articles</h1>

  <div align="center">
    <%= will_paginate %>
  </div>

  <%= render 'article', obj: @articles %>

  <div align="center">
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 align="center">Create an article</h1>

  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h2 align="center"><%= @article.title %></h2>
  <div class="well col xs-8 col xs-offset-2">
    <% if @article.user %>
      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by:</li>
            <li><%= link_to gravatar_for(@article.user, size: 80), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li>
              <small><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %></small>
            </li>
          </div>
        </div>
      </ul>
    <% end %>
    <h4 class="center article-description"><strong>Description: </strong></h4>
    <hr>
    <%= markdown(@article.description) %>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>

    <%= render 'disqus' %>

    <div class="article-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%=  link_to 'Edit', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
          <%= link_to 'Delete this article',
                      article_path(@article),
                      method: :delete,
                      class: 'btn btn-xs btn-danger',
                      data: { confirm: 'Are you sure you want to delete this article?'} %>
      <% end %>
      <%= link_to 'View all articles', articles_path, class: 'btn btn-xs btn-success' %>
    </div>
  </div>
</div>