config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :articles

  resources :categories, except: [:destroy]

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base

  # Relationship
  has_many :article_categories
  has_many :articles, through: :article_categories

  # Validation
  validates :name, presence: true
  validates_uniqueness_of :name
  validates_length_of :name, minimum: 3, maximum: 25

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, only: [:new, :create, :edit, :update]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      flash[:success] = 'You successfully created a new category.'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category name was successfully updated.'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = 'Only admin can peform this action.'
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %>&nbsp;&nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for(@category, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Enter category name', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit 'Create category', class: 'btn btn-primary btn-large' %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1 align="center">Edit Category Name</h1>

  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1 align="center">Listing all categories</h1>

  <div align="center">
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <ul class="listing">
          <div class="row">
            <div class="well col-md-4 col-md-offset-4">
              <li class="article-title">
                <%= link_to category.name, category_path(category) %>
              </li>
              <li><small><%= pluralize(category.articles.count, 'article') %></small></li>
            </div>
          </div>
        </ul>
    <% end %>
    <%= will_paginate %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1 align="center">Create new category</h1>

  <%= render 'shared/errors', obj: @category %>
  <%= form_for(@category, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Enter category name', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit 'Create category', class: 'btn btn-primary btn-large' %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 align="center"><%= "Category: #{@category.name}" %></h1>

  <div class="center">
    <% if logged_in? && current_user.admin? %>
    <div class="row">
      <span class="badge">
        <%= link_to 'Edit category name', edit_category_path(@category) %>
      </span>
    </div>
    <% end %>
    <%= will_paginate @category_articles %>
  </div>

  <%= render 'articles/article', obj: @category_articles %>

  <div class="center">
    <%= will_paginate @category_articles %>
  </div>
</div>